/**
 * Privacy Policy + Terms content (issue #2). EN-only for now.
 *
 * First pass, written to match how the product actually works today (Clerk auth,
 * Neon Postgres, Google Calendar read-only, Anthropic for the find-time prompt,
 * Railway hosting, waitlist email capture). Plain prose, no claims the product
 * can't back. NOT yet counsel-reviewed — that review, and the EN-only vs EN/DE
 * call, are the user's (see the issue). If a DE entity operates the service, an
 * Impressum (§5 DDG) is still owed separately.
 */

export const LEGAL_UPDATED = '9 September 2026';
// TODO(user): confirm the operating entity + a real contact address before launch.
export const LEGAL_CONTACT = 'privacy@findtime.ai';

export type LegalSection = { heading: string; body: string[] };

export const PRIVACY: { title: string; intro: string; sections: LegalSection[] } = {
  title: 'PRIVACY POLICY',
  intro:
    'This policy explains what personal data Find Time collects, why, who it is shared with, and the rights you have under the GDPR. It covers the marketing site, the waitlist, and the Find Time web app.',
  sections: [
    {
      heading: '1. Who is responsible',
      body: [
        `Find Time is operated by the individual trading as Lexora. For any privacy question or to exercise a right below, contact ${LEGAL_CONTACT}.`,
        'If the operating entity is based in Germany, a separate Impressum is published as required by §5 DDG.',
      ],
    },
    {
      heading: '2. What we collect',
      body: [
        'Waitlist: your email address, the page the sign-up came from (a short "source" label), and a salted, irreversible hash of your IP address used only for spam and rate-limit protection. Your raw IP is not stored.',
        'Account: when you sign in, identity and session data are handled by our authentication provider (Clerk) — typically your email address and name. We keep a minimal mirror of your Clerk user id, email and name so the app can attach your calendars and events to you.',
        'Google Calendar (optional): if you connect a Google account, we request read-only access to your calendars and store the events we read, plus encrypted OAuth tokens. We never request write access without asking.',
        'AI scheduling: the text you type into "Ask Find Time" is sent to our AI provider (Anthropic) together with the busy/free times needed to place a block. We do not send event titles or descriptions beyond what the request needs.',
        'Operational logs: standard security and error logs (timestamps, coarse request metadata) generated by our host.',
      ],
    },
    {
      heading: '3. Why we can process it (legal bases)',
      body: [
        'Waitlist — your consent (Art. 6(1)(a)). You can withdraw it any time by asking us to remove your email.',
        'Running the app for you — performance of a contract (Art. 6(1)(b)).',
        'Spam prevention, rate limiting and security logging — our legitimate interest in keeping the service available and abuse-free (Art. 6(1)(f)).',
        'Connecting Google Calendar — your consent, given through Google’s own permission screen.',
      ],
    },
    {
      heading: '4. Processors we use',
      body: [
        'Clerk — authentication and session management.',
        'Neon — managed PostgreSQL database (EU region).',
        'Google — Calendar API, only when you connect an account.',
        'Anthropic — processes the scheduling prompt to produce a structured request.',
        'Railway — application hosting and infrastructure logs.',
        'Each acts as a processor under a data-processing agreement and only on our instructions.',
      ],
    },
    {
      heading: '5. How long we keep it',
      body: [
        'Waitlist entries: until launch invitations are complete or you ask for removal, whichever is first.',
        'Account and calendar data: for as long as your account exists. Deleting your account removes your user row and cascades to your profile, connected accounts, calendars and events; associated Clerk data is deleted too.',
        'Rate-limit counters: rolling, cleared automatically after about two days.',
        'Logs: retained for a short period by our host for security and debugging.',
      ],
    },
    {
      heading: '6. International transfers',
      body: [
        'Data is stored in the EU where possible (Neon EU region). Some processors (Google, Anthropic, Clerk) may process data outside the EU under Standard Contractual Clauses or an adequacy decision.',
      ],
    },
    {
      heading: '7. Your rights',
      body: [
        'You have the right to access, correct, delete, restrict or object to processing of your personal data, and to data portability. Where processing is based on consent, you can withdraw it at any time.',
        `To exercise any of these, email ${LEGAL_CONTACT}. You also have the right to lodge a complaint with your local data protection supervisory authority.`,
      ],
    },
    {
      heading: '8. Cookies',
      body: [
        'The site sets only strictly necessary cookies: your sign-in session and security tokens. There are no analytics, advertising or tracking cookies. If that changes, this policy and the cookie notice will be updated and consent asked for first.',
      ],
    },
    {
      heading: '9. Changes',
      body: [
        `We may update this policy as the product changes. The date at the top reflects the last revision (currently ${LEGAL_UPDATED}).`,
      ],
    },
  ],
};

export const TERMS: { title: string; intro: string; sections: LegalSection[] } = {
  title: 'TERMS OF SERVICE',
  intro:
    'These terms govern your use of Find Time while it is in private beta. By joining the waitlist or using the app you agree to them.',
  sections: [
    {
      heading: '1. The service',
      body: [
        'Find Time is an AI-assisted planning tool, currently in private beta and provided "as is" and "as available". Features may change, break, or be removed without notice.',
      ],
    },
    {
      heading: '2. Your account',
      body: [
        'Sign-in is handled by Clerk. You are responsible for keeping your credentials secure and for activity under your account. You must be old enough to form a binding contract in your country.',
      ],
    },
    {
      heading: '3. Acceptable use',
      body: [
        'Do not misuse the service: no attempts to break, overload, probe, or reverse-engineer it; no automated scraping; no use that infringes others’ rights or breaks the law. We may suspend access that threatens the service or other users.',
      ],
    },
    {
      heading: '4. Beta disclaimer',
      body: [
        'This is pre-release software. We do not guarantee availability, correctness of AI suggestions, or that data will be preserved — beta data may be reset. Always keep your own record of anything important. Review AI-placed blocks before relying on them.',
      ],
    },
    {
      heading: '5. Your content',
      body: [
        'You keep all rights to the tasks, events and text you put into Find Time. You grant us only the permission needed to operate the service for you (store it, display it back to you, send the necessary parts to the processors listed in the Privacy Policy).',
      ],
    },
    {
      heading: '6. Liability',
      body: [
        'To the extent permitted by law, Find Time is not liable for indirect or consequential loss, lost data, or missed commitments arising from use of a beta service. Nothing here excludes liability that cannot be excluded under applicable law.',
      ],
    },
    {
      heading: '7. Termination',
      body: [
        'You can stop using Find Time and delete your account at any time. We may end or suspend the beta, or your access to it, at any time.',
      ],
    },
    {
      heading: '8. Governing law',
      body: [
        'These terms are governed by German law, without prejudice to mandatory consumer-protection rules of your country of residence. We may update these terms as the product changes; continued use after a change means you accept it.',
      ],
    },
    {
      heading: '9. Contact',
      body: [`Questions about these terms: ${LEGAL_CONTACT}.`],
    },
  ],
};
