/**
 * Privacy Policy + Terms content (issue #2). EN-only for now.
 *
 * First pass, written to match how the product actually works today (Clerk auth,
 * Neon Postgres, Google Calendar (read + focus-block write-back), OpenAI for AI features,
 * Railway hosting, waitlist email capture). Plain prose, no claims the product
 * can't back. NOT yet counsel-reviewed — that review, and the EN-only vs EN/DE
 * call, are the user's (see the issue). If a DE entity operates the service, an
 * Impressum (§5 DDG) is still owed separately.
 */

export const LEGAL_UPDATED = '4 October 2026'; // same day: added editing your own Google events
// TODO(user): confirm the operating entity + a real contact address before launch.
export const LEGAL_CONTACT = 'privacy@usefindtime.com';

export type LegalSection = { heading: string; body: string[] };

export const PRIVACY: { title: string; intro: string; sections: LegalSection[] } = {
  title: 'PRIVACY POLICY',
  intro:
    'This policy explains what personal data Find Time collects, why, who it is shared with, and the rights you have under the GDPR. It covers the marketing site, the waitlist, and the Find Time web app.',
  sections: [
    {
      heading: '1. Who is responsible',
      body: [
        `Find Time is operated by the individual trading as Lexora. For any privacy question or to exercise a right below, contact ${LEGAL_CONTACT}.`,
        'If the operating entity is based in Germany, a separate Impressum is published as required by §5 DDG.',
      ],
    },
    {
      heading: '2. What we collect',
      body: [
        'Waitlist: your email address, the page the sign-up came from (a short "source" label), and a salted, irreversible hash of your IP address used only for spam and rate-limit protection. Your raw IP is not stored.',
        'Account: when you sign in, identity and session data are handled by our authentication provider (Clerk) — typically your email address and name. Our database keeps only your Clerk user id, so the app can attach your calendars and events to you; your name and email stay with Clerk. For a connected Google account we keep Google’s anonymous account id, not its email address; the email is read from Google only to show you which account is connected.',
        'What you create in Find Time: tasks, habits, events you add, your planning preferences and your Plan with AI conversations are stored so the app can work for you.',
        'Google Calendar (optional): if you connect a Google account, we request access to read your calendars and to manage events. We store only when your events are (start and end, whether they show as busy, your RSVP and the number of guests) plus encrypted OAuth tokens. Event titles, notes, locations, guest names and video links are not stored: they are read from Google each time you open your calendar, used for that request and discarded. We write to your calendar only when you ask us to, in two cases. First, if you turn on focus-block sync, we add, update and remove Find Time’s own focus blocks as private busy events. Second, when you move, resize or delete one of your own events in Find Time, we make that same change in Google Calendar; this is offered only for one-off events you organise with no other guests, and no one is notified. Find Time never changes your Google events on its own, and never changes meetings with other guests, repeating events or events someone else organised.',
        'Find Time’s use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. We do not sell this data or use it for advertising, and we do not use it to develop, improve or train generalized AI or machine-learning models.',
        'You can disconnect Google at any time in Find Time’s calendar settings, which revokes our access and deletes the stored event times for that account. You can also remove access from your Google Account under Security → Third-party apps & services.',
        'Security: OAuth tokens are encrypted at rest, and all traffic between your browser, our servers and Google is encrypted in transit (TLS).',
        'AI features: when a feature uses an AI model, the text you type is sent to OpenAI, with only the busy/free times needed to answer. OpenAI does not use it for training and keeps it for up to 30 days for abuse monitoring only.',
        'Operational logs: standard security and error logs (timestamps, coarse request metadata) generated by our host.',
        'Cookie choices: when you choose in the cookie banner, we log a random consent ID (also kept in your browser), the date, the version of this policy and what you chose. Nothing that identifies you is stored with it.',
      ],
    },
    {
      heading: '3. Why we can process it (legal bases)',
      body: [
        'Waitlist — your consent (Art. 6(1)(a)). You can withdraw it any time by asking us to remove your email.',
        'Running the app for you — performance of a contract (Art. 6(1)(b)).',
        'Spam prevention, rate limiting and security logging — our legitimate interest in keeping the service available and abuse-free (Art. 6(1)(f)).',
        'Keeping a record of your cookie choice — our legal obligation to be able to show consent (Art. 6(1)(c) with Art. 7(1)).',
        'Connecting Google Calendar — your consent, given through Google’s own permission screen.',
      ],
    },
    {
      heading: '4. Processors we use',
      body: [
        'Clerk — authentication and session management. Clerk uses Cloudflare to protect its sign-in service from bots.',
        'Neon — managed PostgreSQL database (EU region).',
        'Google — Calendar API when you connect an account.',
        'OpenAI — to turn a typed request into a structured one. OpenAI does not use API data for training and keeps it for up to 30 days for abuse monitoring.',
        'Railway — application hosting and infrastructure logs.',
        'Each acts as a processor under a data-processing agreement and only on our instructions.',
      ],
    },
    {
      heading: '5. How long we keep it',
      body: [
        'Waitlist entries: until launch invitations are complete or you ask for removal, whichever is first.',
        'Account and calendar data: for as long as your account exists. Deleting your account removes your user row and cascades to your profile, connected accounts, calendars and events; associated Clerk data is deleted too.',
        'Rate-limit counters: rolling, cleared automatically after about two days.',
        'Cookie-choice log: 3 years, then deleted automatically. Your browser keeps the choice for 12 months, after which we ask again.',
        'Logs: retained for a short period by our host for security and debugging.',
      ],
    },
    {
      heading: '6. International transfers',
      body: [
        'Data is stored in the EU where possible (Neon EU region). Some processors (Google, Clerk, OpenAI, Railway) may process data outside the EU under Standard Contractual Clauses or an adequacy decision.',
      ],
    },
    {
      heading: '7. Your rights',
      body: [
        'You have the right to access, correct, delete, restrict or object to processing of your personal data, and to data portability. Where processing is based on consent, you can withdraw it at any time.',
        `To exercise any of these, email ${LEGAL_CONTACT}. You also have the right to lodge a complaint with your local data protection supervisory authority.`,
      ],
    },
    {
      heading: '8. Cookies',
      body: [
        'Find Time stores only what is strictly necessary on your device: cookies that keep you signed in and protect sign-in from bots, plus a few settings in your browser’s storage (for example the calendar background you picked). Sign-in cookies are set only on the sign-in pages and inside the app, never while you just read this site. These need no consent under §25(2) TDDDG / Art. 5(3) ePrivacy Directive. There are no analytics, advertising or tracking cookies.',
        'Fonts are served from our own server, so no request goes to Google Fonts when you load a page.',
        'If we ever add anything optional, it stays off until you agree in the cookie banner, and you can change or withdraw your choice at any time with “Cookie settings” at the bottom of every page or the button below. The full list of what is stored, by whom and for how long:',
      ],
    },
    {
      heading: '9. Changes',
      body: [
        `We may update this policy as the product changes. The date at the top reflects the last revision (currently ${LEGAL_UPDATED}).`,
      ],
    },
  ],
};

export const TERMS: { title: string; intro: string; sections: LegalSection[] } = {
  title: 'TERMS OF SERVICE',
  intro:
    'These terms govern your use of Find Time while it is in private beta. By joining the waitlist or using the app you agree to them.',
  sections: [
    {
      heading: '1. The service',
      body: [
        'Find Time is an AI-assisted planning tool, currently in private beta and provided "as is" and "as available". Features may change, break, or be removed without notice.',
      ],
    },
    {
      heading: '2. Your account',
      body: [
        'Sign-in is handled by Clerk. You are responsible for keeping your credentials secure and for activity under your account. You must be old enough to form a binding contract in your country.',
      ],
    },
    {
      heading: '3. Acceptable use',
      body: [
        'Do not misuse the service: no attempts to break, overload, probe, or reverse-engineer it; no automated scraping; no use that infringes others’ rights or breaks the law. We may suspend access that threatens the service or other users.',
      ],
    },
    {
      heading: '4. Beta disclaimer',
      body: [
        'This is pre-release software. We do not guarantee availability, correctness of AI suggestions, or that data will be preserved — beta data may be reset. Always keep your own record of anything important. Review AI-placed blocks before relying on them.',
      ],
    },
    {
      heading: '5. Your content',
      body: [
        'You keep all rights to the tasks, events and text you put into Find Time. You grant us only the permission needed to operate the service for you (store it, display it back to you, send the necessary parts to the processors listed in the Privacy Policy).',
      ],
    },
    {
      heading: '6. Liability',
      body: [
        'To the extent permitted by law, Find Time is not liable for indirect or consequential loss, lost data, or missed commitments arising from use of a beta service. Nothing here excludes liability that cannot be excluded under applicable law.',
      ],
    },
    {
      heading: '7. Termination',
      body: [
        'You can stop using Find Time and delete your account at any time. We may end or suspend the beta, or your access to it, at any time.',
      ],
    },
    {
      heading: '8. Governing law',
      body: [
        'These terms are governed by German law, without prejudice to mandatory consumer-protection rules of your country of residence. We may update these terms as the product changes; continued use after a change means you accept it.',
      ],
    },
    {
      heading: '9. Contact',
      body: [`Questions about these terms: ${LEGAL_CONTACT}.`],
    },
  ],
};
